{% set name = "tilepie" %}
{% set version = "0.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 21c63a35b52800957b0af1f15d33acc80c372db8305c8ecea6bc3335fd34221b

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv "
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - tilepie

about:
  home: https://github.com/kamicut/tilepie
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: multiproc mbtile processing
  dev_url: https://github.com/kamicut/tilepie

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - benhuff
    - adbeda
